EyeWitness.GUI.Identity/Models/EvaluationViewModel.cs
using EyeWitness.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EyeWitness.GUI.Identity.Models
{
    public class EvaluationViewModel
    {
        public DateTime evaluationDate { get; set; }
        public string comment { get; set; }
        public string video { get; set; }
        public int rating { get; set; }
        public string picture { get; set; }

        public int UserId { get; set; }
        public virtual User user { get; set; }
        public IEnumerable<Evaluation> evaluations { get; set; }
    }
}

EyeWitness.GUI.Identity/Models/EvaluationsViewModel.cs
using EyeWitness.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EyeWitness.GUI.Identity.Models
{
    public class EvaluationsViewModel
    {
        public EvaluationsViewModel()
        {
            Ratings = new List<SelectListItem>();
            Ratings.Add(new SelectListItem() { Text = "1", Value = "1" });
            Ratings.Add(new SelectListItem() { Text = "2", Value = "2" });
            Ratings.Add(new SelectListItem() { Text = "3", Value = "3" });
            Ratings.Add(new SelectListItem() { Text = "4", Value = "4" });
            Ratings.Add(new SelectListItem() { Text = "5", Value = "5" });
        }
        public EvaluationsViewModel(Evaluation e)
        {
            UserImageUrl = e.user.avatar;
            UserFirstName = e.user.firstName;
            UserLastName = e.user.lastName;
            DateOfEvaluation = e.evaluationDate;
            VideoUrl = e.video;
            Rating = e.rating;
            Description = e.comment;
            ImagesUrls = e.GetPicturesUrls();
        }
        public int WitnessCardId { get; set; }
        public WitnessCard WitnessCard { get; set; }
        public string UserImageUrl { get; set; }
        public string UserFirstName { get; set; }
        public string UserLastName { get; set; }
        public DateTime DateOfEvaluation { get; set; }
        public string VideoUrl { get; set; }
        public int Rating { get; set; }
        public List<SelectListItem> Ratings { get; set; }
        public string Description { get; set; }
        public string[] ImagesUrls { get; set; }
    }
}

EyeWitness.GUI.Identity/Controllers/EvaluationController.cs
using EyeWitness.Domain.Entities;
using EyeWitness.Services.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EyeWitness.GUI.Identity.Helpers;
using EyeWitness.GUI.Identity.Models;
using System.IO;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity;
using System.Net.Mail;

namespace EyeWitness.GUI.Identity.Controllers
{
    public class EvaluationController : Controller
    {
        EvaluationServices evaluationServices;
        WitnessCardServices witnessCardServices;

        public ApplicationUserManager UserManager
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
        }

        public EvaluationController()
        {
            evaluationServices = new EvaluationServices();
            witnessCardServices = new WitnessCardServices();
        }

        // GET: Evaluation/Index/5
        public ActionResult Index(int id)
        {
            WitnessCard witnessCardFound = witnessCardServices.GetById(id);
            IEnumerable<Evaluation> evals = evaluationServices.GetEvaluationsOrderedByDate(witnessCardFound);

            return View(evals.ToViewModelEnumerable());
        }


        public ActionResult Create(int id)
        {
            EvaluationsViewModel model = new EvaluationsViewModel();
            model.WitnessCardId = id;
            model.WitnessCard = witnessCardServices.GetById(id);
            model.UserImageUrl = "/Content/_Uploads/TeamMembers/ahmed_moalla.jpg";
            model.UserFirstName = "Ahmed";
            model.UserLastName = "Agent";
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(EvaluationsViewModel model)
        {

            if (ViewData.ModelState.IsValid)
            {
                var video = Request.Files.Get(0);
                string picturesUrl = "";
                string videoUrl = video.FileName;


                for (int i = 1; i < Request.Files.Count; i++)
                {
                    HttpPostedFileBase img = Request.Files[i];
                    picturesUrl += img.FileName + Evaluation.PICTURE_SEPARATOR;
                }

                Evaluation eval = new Evaluation()
                {
                    evaluationDate = DateTime.Now,
                    comment = model.Description,
                    rating = model.Rating,
                    UserId = 1,
                    WitnessCardId = model.WitnessCardId,
                    video = videoUrl,
                    pictures = picturesUrl
                };

                evaluationServices.Add(eval);
                evaluationServices.Commit();

                //Saving images
                for (int i = 1; i < Request.Files.Count; i++)
                {
                    HttpPostedFileBase img = Request.Files[i];
                    var path = Path.Combine(Server.MapPath("~/Content/_Uploads/Images"), img.FileName);
                    img.SaveAs(path);
                }

                // Saving video
                video.SaveAs(Path.Combine(Server.MapPath("~/Content/_Uploads/Videos"), video.FileName));


                return RedirectToAction("Index", new { id = model.WitnessCardId });
            }

            return View();
        }

        public ActionResult MyEvaluation()
        {
            ApplicationUserManager UserManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            int idConnectedUSer = UserManager.FindById(User.Identity.GetUserId()).UserInfo.Id;

            List<MyEvaluationsModel> ListEvaluations = new List<MyEvaluationsModel>();
            var evaluationList = evaluationServices.GetEvaluationsByUserId(idConnectedUSer);
            foreach (var item in evaluationList)
            {
                ListEvaluations.Add(new MyEvaluationsModel

                {

                    evaluationDate = item.evaluationDate,
                    WCname = (witnessCardServices.GetById((long)item.WitnessCardId)).name,
                    WCDescription = (witnessCardServices.GetById((long)item.WitnessCardId)).description,

                });

            }
            return View(ListEvaluations);
        }

        // GET: Evaluation
        public ActionResult FollowedEvaluations()
        {
            User currentUser = UserManager.FindById(User.Identity.GetUserId()).UserInfo;

            List<EvaluationViewModel> evaluationviewmodel = new List<EvaluationViewModel>();
            List<Evaluation> evaluations = evaluationServices.GetEvaluationsOfFollowedUsersByUserId(currentUser.Id).ToList();
            foreach (Evaluation eval in evaluations)
            {
                evaluationviewmodel.Add(
                     new EvaluationViewModel()
                     {
                         rating = eval.rating,
                         picture = eval.GetPicturesUrls()[0],
                         video = eval.video,
                         comment = eval.comment,
                         evaluationDate = eval.evaluationDate
                     });
            }

            return View(evaluationviewmodel);
        }


    }
}

EyeWitness.GUI.Identity/Views/Evaluation/Create.cshtml
@model EyeWitness.GUI.Identity.Models.EvaluationsViewModel

@section stylesheets {
    <link rel="stylesheet" href="~/Content/css/evaluation.css" />
}

<h4>Your evaluation about witness card : "@Model.WitnessCard.name"</h4>

@using (Html.BeginForm("Create", "Evaluation", FormMethod.Post, new { enctype = "multipart/form-data", @class = "card row eval-card" }))
{
    <div class="eval-header row col s12">
        <img class="z-depth-1 eval-userimage col s2" src="@Url.Content(Model.UserImageUrl)" />
        <div class="eval-name-date col s5">
            <h5>@Model.UserFirstName @Model.UserLastName</h5>
        </div>
        <span class="eval-rating col s1 offset-s4 right valign-wrapper">
            <span>0</span>
            <i class="material-icons">star</i>
        </span>
    </div>

        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.WitnessCardId)

        <div class="input-field col s12">
            @Html.LabelFor(model => model.Description)
            @Html.TextAreaFor(model => model.Description, htmlAttributes: new { @class = "materialize-textarea" })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>

        @Html.LabelFor(model => model.VideoUrl, htmlAttributes: new { @class = "col s12" })
        <div class="col s10 offset-s1 create-evaluation-video-placeholder valign-wrapper">
            <img src="~/Content/img/video_placeholder.png" />
            @Html.ValidationMessageFor(model => model.VideoUrl)
            @Html.TextBox("Video", null, new { type = "file", style = "display: none", accept = "video/*" })
            <div class="eval-video-container">
                <i class="video-close-button material-icons tooltipped" data-position="bottom" data-delay="50" data-tooltip="Replace this video">close</i>
                <video height="450" controls></video>
            </div>
        </div>

        @Html.LabelFor(model => model.ImagesUrls, htmlAttributes: new { @class = "col s12" })
        <div class="col s12 create-evaluation-image-placeholder row">
            <div class="col s3 valign-wrapper">
                <img src="/Content/img/image_placeholder.png" class="add-image-file" />
            </div>

        </div>

        @Html.LabelFor(model => model.Rating, htmlAttributes: new { @class = "col s12" })
        <div class="col s12 valign-wrapper create-eval-rating">
            @Html.HiddenFor(model => model.Rating)
            <div class="stars">
                <i class="fa fa-star-o"></i>
                <i class="fa fa-star-o"></i>
                <i class="fa fa-star-o"></i>
                <i class="fa fa-star-o"></i>
                <i class="fa fa-star-o"></i>
            </div>
        </div>

        <div class="col s12 valign-wrapper">
            <input type="submit" value="Submit" class="btn btn-default" />
        </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { id = Model.WitnessCardId })
</div>

@section Scripts {
    <script>
        $('select').material_select();
    </script>
    <script type="text/javascript" src="~/Content/js/evaluation_create.js"></script>
}

EyeWitness.GUI.Identity/Views/Evaluation/FollowedEvaluations.cshtml
@model IEnumerable<EyeWitness.GUI.Identity.Models.EvaluationViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@foreach (var item in Model)



{
    <div class="card row eval-card">
        <div class="eval-header row col s12">
            <img class="z-depth-1 eval-userimage col s2" src="@Url.Content(item.user.avatar)" />
            <div class="eval-name-date col s5">
                <h5>@item.user.firstName @item.user.lastName</h5>
                <span>@item.evaluationDate.ToLongDateString() </span>
            </div>
            <span class="eval-rating col s1 offset-s4 right valign-wrapper">
                <span>@item.rating</span>
                <i class="material-icons">star</i>
            </span>
        </div>
        <p class="col s12">
            @item.comment
        </p>
        <video controls name="media" class="col s10 offset-s1">
            <source src="@Url.Content("~/Content/_Uploads/Videos/" + item.video)" />
        </video>


    </div>

}

EyeWitness.GUI.Identity/Views/Evaluation/Index.cshtml
@model IEnumerable<EyeWitness.GUI.Identity.Models.EvaluationsViewModel>
@using EyeWitness.GUI.Identity.Models

@section stylesheets {
    <link rel="stylesheet" type="text/css" href="/Content/css/slick.css" />
    <link rel="stylesheet" type="text/css" href="/Content/css/slick-theme.css" />
    <link rel="stylesheet" href="/Content/css/evaluation.css" />
}

@section Scripts {
    <script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script type="text/javascript" src="/Content/js/slick.js"></script>
    <script type="text/javascript" src="/Content/js/evaluation.js"></script>

    <script>
        $(document).ready(function () {
            $('.materialboxed').materialbox();
        });
    </script>
}

@foreach (EvaluationsViewModel e in Model)
{
    <div class="card row eval-card">
        <div class="eval-header row col s12">
            <img class="z-depth-1 eval-userimage col s2" src="@Url.Content(e.UserImageUrl)" />
            <div class="eval-name-date col s5">
                <h5>@e.UserFirstName @e.UserLastName</h5>
                <span>@e.DateOfEvaluation.ToLongDateString() At @e.DateOfEvaluation.TimeOfDay.ToString()</span>
            </div>
            <span class="eval-rating col s1 offset-s4 right valign-wrapper">
                <span>@e.Rating</span>
                <i class="material-icons">star</i>
            </span>
        </div>

        <p class="col s12">
            @e.Description
        </p>

        <video controls name="media" class="col s10 offset-s1">
            <source src="@Url.Content("~/Content/_Uploads/Videos/" + e.VideoUrl)" />
        </video>

        <div class="eval-image-slider col s12">
            @foreach (string imgUrl in e.ImagesUrls)
                {
                    if (imgUrl != "")
                    {
                    <div>
                        <img class="eval-thumbnail-image materialboxed" src="@Url.Content("~/Content/_Uploads/Images/" + imgUrl)" />
                    </div>
                }
            }
        </div>


    </div>

}

EyeWitness.GUI.Identity/Views/Evaluation/MyEvaluation.cshtml
@model IEnumerable<EyeWitness.GUI.Identity.Models.MyEvaluationsModel>

@{
    ViewBag.Title = "MyEvalution";
}

<h2>MyEvalution</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.evaluationDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EvalutionID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.WCname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.WCDescription)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.evaluationDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EvalutionID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.WCname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.WCDescription)
        </td>
        <td>
           @Html.ActionLink("take a look !", "EvaluationDetail", new { IdEvaluation=item.EvalutionID  }) 
          @*  <a href="javascript:void(0);" class="anchorDetail" data-id="@item.EvalutionID">Details</a>  *@
        </td>
    </tr>
}

</table>