EyeWitness.GUI.Identity/Models/WitnessCardViewModel.cs
using EyeWitness.Domain.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace EyeWitness.GUI.Identity.Models
{
    public class WitnessCardViewModel
    {

        public string crateria1 { get; set; }
        public string crateria2 { get; set; }
        public string crateria3 { get; set; }
        [Range(1, 5,ErrorMessage = "Note must be between 1 and 5")]
        public int note1 { get; set; }
        [Range(1, 5,ErrorMessage = "Note must be between 1 and 5")]
        public int note2 { get; set; }
        [Range(1, 5,ErrorMessage = "Note must be between 1 and 5")]
        public int note3 { get; set; }
    }
}

EyeWitness.GUI.Identity/Controllers/WitnessCardController.cs
using EyeWitness.Domain.Entities;
using EyeWitness.GUI.Identity.Helpers;
using EyeWitness.GUI.Identity.Models;
using EyeWitness.Services.Repositories;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EyeWitness.GUI.Identity.Controllers
{
    public class WitnessCardController : Controller
    {
        WitnessCardServices witnessCardServices = null;
        CategoryServices categoryServices = null;
        SubscribeService subscribeService;
        SuggestionService suggestionService;

        public WitnessCardController()
        {
            witnessCardServices = new WitnessCardServices();
            categoryServices = new CategoryServices();
            subscribeService = new SubscribeService();
            suggestionService = new SuggestionService();
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
        }

        public ActionResult Index()
        {
            return View();
        }

        // GET: WitnessCard
        public ActionResult MyWitnessCards()
        {
            var witnessCard = witnessCardServices.GetUnpublishedCardByUserId(UserManager.FindById(User.Identity.GetUserId()).UserInfo.Id);
            List<WitnessCardModel> WCM = new List<WitnessCardModel>();
            foreach (var item in witnessCard)
            {
                WCM.Add(
                    new WitnessCardModel
                    {
                        name = item.name,
                        description = item.description,
                        picture = item.picture,
                        //CategoryId = item.CategoryId
                        Id = item.Id,
                        status = item.status
                    });
            }
            return View(WCM);
        }

        public ActionResult Suggest(int id)
        {
            SuggestModel WC = new SuggestModel()
            {
                IdWC = id

            };

            return View(WC);

        }
        // POST: WitnessCard/Create
        [HttpPost]
        public ActionResult Suggest(SuggestModel suggest)
        {
            //if (!ModelState.IsValid || Image == null || Image.ContentLength == 0)
            //{
            //    RedirectToAction("Create");

            //}
            // User.Identity.GetUserId();
            int UserId = UserManager.FindById(User.Identity.GetUserId()).UserInfo.Id;


            int Id = suggest.IdWC;
            string Name = suggest.name;
            SuggestionWC suggestionWC = new SuggestionWC()
            {
                SuggestingUserId = UserId,
                SuggestedUserId = 2,
                SuggestedCardId = Id,
                DateSuggestion = DateTime.Now
            };

            witnessCardServices.Suggest(suggestionWC);
            witnessCardServices.Commit();

            return RedirectToAction("Index");

        }


        public ActionResult ListOfWCSuggested()
        {
            int UserId = UserManager.FindById(User.Identity.GetUserId()).UserInfo.Id;
            var witnessCard = witnessCardServices.ListOfWCSuggested(UserId);
            List<WitnessCardModel> WCM = new List<WitnessCardModel>();
            foreach (var item in witnessCard)
            {
                WCM.Add(
                    new WitnessCardModel
                    {
                        name = item.name,
                        description = item.description,
                        picture = item.picture,
                        //CategoryId = item.CategoryId
                        Id = item.Id
                    });




            }
            return View(WCM);
        }

        [HttpPost]
        public ActionResult Index(String searchString)
        {

            var witnessCard = witnessCardServices.GetAll();
            List<WitnessCardModel> WCM = new List<WitnessCardModel>();
            foreach (var item in witnessCard)
            {
                WCM.Add(
                    new WitnessCardModel
                    {
                        name = item.name,
                        description = item.description,
                        picture = item.picture,
                        //CategoryId = item.CategoryId,
                        Id = item.Id
                    });
            }

            if (!String.IsNullOrEmpty(searchString)) { WCM = WCM.Where(m => m.name.Contains(searchString)).ToList(); }
            return View(WCM);
        }


        // GET: WitnessCard/Details/5
        public ActionResult Details(int id)
        {
            WitnessCard wc = witnessCardServices.GetById(id);

            WitnessCardModel WCM = new WitnessCardModel
            {
                name = wc.name,
                description = wc.description,
                picture = wc.picture,
                //CategoryId = item.CategoryId
                Id = wc.Id,
                Localisation = wc.Address,


            };

            WCM.Category = categoryServices.GetAll().ToSelectListItems();

            return View(WCM);

        }

        // GET: WitnessCard/Create
        public ActionResult Create()
        {
            var WCModel = new WitnessCardModel();
            WCModel.Category = categoryServices.GetAll().ToSelectListItems();
            return View(WCModel);

        }
        
        // POST: WitnessCard/Create
        [HttpPost]
        public ActionResult Create(WitnessCardModel wc, HttpPostedFileBase Image)
        {
            //if (!ModelState.IsValid || Image == null || Image.ContentLength == 0)
            //{
            //    RedirectToAction("Create");

            //}

            wc.picture = Image.FileName;
            WitnessCard witnessCard = new WitnessCard
            {

                name = wc.name,
                description = wc.description,
                picture = wc.picture,
                creatorId = UserManager.FindById(User.Identity.GetUserId()).UserInfo.Id,
                note = 0,
                CategoryId = wc.CategoryId,
                Address = wc.Localisation
            };

            witnessCardServices.Add(witnessCard);
            witnessCardServices.Commit();
            var path = Path.Combine(Server.MapPath("~/Content/_Uploads/Images/"), Image.FileName);
            Image.SaveAs(path);
            return RedirectToAction("MyWitnessCards");

        }

        // GET: WitnessCard/Edit/5
        public ActionResult Edit(int id)
        {
            WitnessCard wc = witnessCardServices.GetById(id);

            WitnessCardModel WCM = new WitnessCardModel
            {
                name = wc.name,
                description = wc.description,
                picture = wc.picture,
                //CategoryId = item.CategoryId
                Id = wc.Id,
                Localisation = wc.Address,


            };

            WCM.Category = categoryServices.GetAll().ToSelectListItems();

            return View(WCM);

        }

        // POST: WitnessCard/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, WitnessCardModel wc, HttpPostedFileBase Image)
        {
            WitnessCard witnessCard = witnessCardServices.GetById(id);
            wc.picture = Image.FileName;

            witnessCard.name = wc.name;
            witnessCard.description = wc.description;
            witnessCard.picture = wc.picture;
            witnessCard.note = 0;
            witnessCard.CategoryId = wc.CategoryId;
            witnessCard.Address = wc.Localisation;
            
            witnessCardServices.Update(witnessCard);
            witnessCardServices.Commit();
            var path = Path.Combine(Server.MapPath("~/Content/Upload/"), Image.FileName);
            Image.SaveAs(path);
            return RedirectToAction("Index");

        }

        // GET: WitnessCard/Delete/5
        public ActionResult Delete(int id)
        {
            WitnessCard wc = witnessCardServices.GetById(id);

            WitnessCardModel WCM = new WitnessCardModel
            {
                name = wc.name,
                description = wc.description,
                picture = wc.picture,
                //CategoryId = item.CategoryId
                Id = wc.Id
            };
            WCM.Category = categoryServices.GetAll().ToSelectListItems();
            return View(WCM);

        }

        // POST: WitnessCard/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            WitnessCard witnessCard = witnessCardServices.GetById(id);
            witnessCardServices.Delete(witnessCard);
            witnessCardServices.Commit();
            return RedirectToAction("Index");
        }
        public ActionResult Afficher(int CategoryId)
        {
            List<WitnessCard> wc = witnessCardServices.GetAllByCategoryId(CategoryId).ToList();
            List<WitnessCardModel> WCM = new List<Models.WitnessCardModel>();
            foreach (var item in wc)
            {
                WCM.Add(
                    new WitnessCardModel
                    {
                        name = item.name,
                        description = item.description,
                        picture = item.picture,
                        //CategoryId = item.CategoryId,
                        Id = item.Id
                    });
            }
            return View(WCM);
        }
        public ActionResult Publish(int id)
        {
            witnessCardServices.publishWC(id);
            return RedirectToAction("MyWitnessCards");
        }
        public ActionResult Lister()
        {
            var Categories = categoryServices.GetAll();
            List<CategoryModel> WCM = new List<CategoryModel>();
            foreach (var item in Categories)

EyeWitness.GUI.Identity/Views/WitnessCard/Afficher.cshtml
@model IEnumerable<EyeWitness.GUI.Identity.Models.WitnessCardModel>
@using EyeWitness.GUI.Identity.Models;
@{
    ViewBag.Title = "Afficher";
}
<div style="font-family:Arial">
    <h2>Witness List</h2>
    <ul>
        
       @foreach (WitnessCardModel wcm in @Model)
       {
           <li>
               @Html.ActionLink(wcm.name,"Details",new { id=wcm.Id})
           </li>
       }
    </ul>

</div>

EyeWitness.GUI.Identity/Views/WitnessCard/Create.cshtml
@model EyeWitness.GUI.Identity.Models.WitnessCardModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "WitnessCard", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>WitnessCardModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.picture, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("Image", null, new { type = "file" })
                @Html.ValidationMessageFor(model => model.picture, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CategoryId, Model.Category, "select")
                @Html.ValidationMessageFor(model => model.CategoryId)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Localisation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Localisation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Localisation, "", new { @class = "text-danger" })
            </div>
        </div>

        <style>
            html, body {
                height: 100%;
                margin: 0;
                padding: 0;
            }

            #map {
                height: 100%;
            }
        </style>

        <div id="map"></div>
        <form action="">
        <input type="hidden" name="lat" id="lat" />
        <input type="hidden" name="lng" id="lng" />
        </form>
        <script>
            
            // The following example creates a marker in Stockholm, Sweden using a DROP
            // animation. Clicking on the marker will toggle the animation between a BOUNCE
            // animation and no animation.

            var marker;
            var latitude = document.getElementById("Latitude").value;
            var longitude = document.getElementById("Longitude").value;
            function initMap() {
                var map = new google.maps.Map(document.getElementById('map'), {
                    zoom: 8,
                    center: { lat: 36.7948623, lng: 10.0732376 }
                });

                marker = new google.maps.Marker({
                    map: map,
                    draggable: true,
                    animation: google.maps.Animation.DROP,
                    position: { lat: 36.7948623, lng: 10.0732376 }
                });
                marker.addListener('click', toggleBounce);
                //marker.setPosition(tx);
                google.maps.event.addListener(marker, 'dragend', function () {
                    var lat = marker.getPosition().lat();
                    var lng = marker.getPosition().lng();
                    /*marke
                    $('#lat').val(lat);
                    $('#lng').val(lng);*/
                    /*$.ajax({
                        url: "http://maps.googleapis.com/maps/api/geocode/json?latlng=" + lat + "," + lng + "&sensor=true",
                        success: function (res) {
                            console.log(res.results[0].formatted_address);
                        }
                    })*/

                    var latlng = new google.maps.LatLng(lat, lng);
                    var geocoder = geocoder = new google.maps.Geocoder();
                    geocoder.geocode({ 'latLng': latlng }, function (results, status) {
                        if (status == google.maps.GeocoderStatus.OK) {
                            if (results[1]) {
                                //alert("Location: " + results[1].formatted_address);
                                $("#Localisation").val(results[1].formatted_address);
                            }
                        }
                    });

                });
                google.maps.event.addListener(marker, 'tx', function () {
                    var tx = marker.setPosition().tx();
                    $('#tx').val(tx);

                });
            }

            function toggleBounce() {
                if (marker.getAnimation() !== null) {
                    marker.setAnimation(null);
                } else {
                    marker.setAnimation(google.maps.Animation.BOUNCE);
                }
            }
        </script>
        <script async defer
                src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBCVSBoBAUjAfb-Pfx_qq0ZKUHCitbzsl4&signed_in=true&callback=initMap"></script>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EyeWitness.GUI.Identity/Views/WitnessCard/Details.cshtml
@model EyeWitness.GUI.Identity.Models.WitnessCardModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

@*<div>
    <h4>WitnessCardModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.picture)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.picture)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Localisation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Localisation)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>*@

@{string path = "~/Content/Upload/" + @Model.picture;}
<div class="col s4">
    <p><h6>Name:</h6>@Model.name</p>
    <img alt="WitnessCard" src="@Url.Content(path)" width="200" height="200" />
    <p><h6>Description:</h6>@Model.description</p>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Localisation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Localisation)
        </dd>

        </dl>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Back to List", "Index")
</div>

EyeWitness.GUI.Identity/Views/WitnessCard/Edit.cshtml
@model EyeWitness.GUI.Identity.Models.WitnessCardModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "WitnessCard", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>WitnessCardModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.picture, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("Image", null, new { type = "file" })
                @Html.ValidationMessageFor(model => model.picture, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CategoryId, Model.Category, "select")
                @Html.ValidationMessageFor(model => model.CategoryId)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Localisation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Localisation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Localisation, "", new { @class = "text-danger" })
            </div>
        </div>
        <html>
        <head>
            <meta charset="utf-8">
            <title>Marker Animations</title>
            <style>
                html, body {
                    height: 100%;
                    margin: 0;
                    padding: 0;
                }

                #map {
                    height: 100%;
                }
            </style>
        </head>
        <body>
            <div id="map"></div>
            <form action="">
                <input type="hidden" name="lat" id="lat" />
                <input type="hidden" name="lng" id="lng" />
            </form>
            <script>

                    // The following example creates a marker in Stockholm, Sweden using a DROP
                    // animation. Clicking on the marker will toggle the animation between a BOUNCE
                    // animation and no animation.

                    var marker;
                    var latitude = document.getElementById("Latitude").value;
                    var longitude = document.getElementById("Longitude").value;
                    function initMap() {
                        var map = new google.maps.Map(document.getElementById('map'), {
                            zoom: 13,
                            center: { lat: 59.325, lng: 18.070 }
                        });

                        marker = new google.maps.Marker({
                            map: map,
                            draggable: true,
                            animation: google.maps.Animation.DROP,
                            position: { lat: 59.327, lng: 18.067 }
                        });
                        marker.addListener('click', toggleBounce);
                        //marker.setPosition(tx);
                        google.maps.event.addListener(marker, 'dragend', function () {
                            var lat = marker.getPosition().lat();
                            var lng = marker.getPosition().lng();
                            /*marke
                            $('#lat').val(lat);
                            $('#lng').val(lng);*/
                            /*$.ajax({
                                url: "http://maps.googleapis.com/maps/api/geocode/json?latlng=" + lat + "," + lng + "&sensor=true",
                                success: function (res) {
                                    console.log(res.results[0].formatted_address);
                                }
                            })*/

                            var latlng = new google.maps.LatLng(lat, lng);
                            var geocoder = geocoder = new google.maps.Geocoder();
                            geocoder.geocode({ 'latLng': latlng }, function (results, status) {
                                if (status == google.maps.GeocoderStatus.OK) {
                                    if (results[1]) {
                                        //alert("Location: " + results[1].formatted_address);
                                       $("#Localisation").val(results[1].formatted_address);
                                    }
                                }
                            });

                        });
                        google.maps.event.addListener(marker, 'tx', function () {
                            var tx = marker.setPosition().tx();
                            $('#tx').val(tx);

                        });
                    }

                    function toggleBounce() {
                        if (marker.getAnimation() !== null) {
                            marker.setAnimation(null);
                        } else {
                            marker.setAnimation(google.maps.Animation.BOUNCE);
                        }
                    }
            </script>
            <script async defer
                    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBCVSBoBAUjAfb-Pfx_qq0ZKUHCitbzsl4&signed_in=true&callback=initMap"></script>
        </body>
    </html>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

EyeWitness.GUI.Identity/Views/WitnessCard/Index.cshtml
@{
    ViewBag.Title = "Witness Card Name";
}

@section stylesheets {
    <link rel="stylesheet" href="~/Content/css/witnesscard.css" />
}

@section Scripts {
<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBg_88ff4Dx64Y7tl4rsx9O8ev7RJA9BCA&callback=initMap">
</script>
    <script type="text/javascript" src="~/Content/js/witnesscard.js"></script>

}
<div class="container">
    <div class="row">
        <div class="witness-card-content col s12">
            <div class="witness-card-header row valign-wrapper">
                <div class="witness-card-subscribe s12">
                    <div class="subscribe-btn">
                        <i class="material-icons">remove_red_eye</i>
                        <div>Subscribe</div>
                    </div>
                    
                    <div class="number">250</div>
                </div>
                <div class="valign valign-wrapper">
                    <img class="witness-card-logo z-depth-2 s12 valign" src="/Content/img/logo.png" alt="logo" />
                    <h5 class="witness-card-title s12">Witness Card Name</h5>
                    <div class="witness-card-rating s12 valign">
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                    </div>
                </div>
                
            </div>
            <div class="witness-card-infos">
                <h3 class="section-title">General Informations</h3>
                <ul class="row card">
                    <li class="col s12">
                        <label><i class="fa fa-list"></i> Description</label>
                        <p>
                            Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?
                        </p>
                    </li>
                    <li class="col s6">
                        <label><i class="fa fa-map-marker"></i>Address :</label> 5, Rue de Tunis
                    </li>
                    <li class="col s6">
                        <label><i class="fa fa-phone"></i>Phone :</label> +21652911990
                    </li>
                    <li class="col s12">
                        <label><i class="fa fa-list"></i>Ambience :</label>
                        <div class="row">
                            <div class="col s3">Ambience</div>
                            <div class="col s3">Ambience</div>
                            <div class="col s3">Ambience</div>
                            <div class="col s3">Ambience</div>
                        </div>
                    </li>
                    <li class="col s12">
                        <label>Offered services :</label>
                        <div class="row">
                            <div class="col s3">Service</div>
                            <div class="col s3">Service</div>
                            <div class="col s3">Service</div>
                        </div>
                    </li>
                    <li class="col s12">
                        <label><i class="fa fa-credit-card"></i>Means of payment :</label>
                        <div class="row">
                            <div class="col s3">Service</div>
                            <div class="col s3">Service</div>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="witness-card-map">
                <h3 class="section-title">Location</h3>
                <div>
                    <div id="map"></div>
                </div>
            </div>
            <div class="witness-card-rating"></div>
            <div class="witness-card-evaluations">

            </div>
        </div>
        
    </div>
</div>

EyeWitness.GUI.Identity/Views/WitnessCard/ListOfWCSuggested.cshtml
@model IEnumerable<EyeWitness.GUI.Identity.Models.WitnessCardModel>

<p>
    @Html.ActionLink("List Of WitnessCard Suggested", "ListOfWCSuggested")
</p>

@if (Model != null)
{
    foreach (var item in Model)
    {
        @Html.Partial("PartialViewWCSuggest", item);
    }
}

EyeWitness.GUI.Identity/Views/WitnessCard/Lister.cshtml
@model IEnumerable<EyeWitness.GUI.Identity.Models.CategoryModel>

@{
    ViewBag.Title = "Lister";
}

<h2>Lister</h2>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td>
            @Html.ActionLink("Consulter", "Afficher", new { categoryId=item.IDCat }) |
        </td>
    </tr>
}

</table>

EyeWitness.GUI.Identity/Views/WitnessCard/MyWitnessCards.cshtml
@model IEnumerable<EyeWitness.GUI.Identity.Models.WitnessCardModel>


@ViewBag.Id
@ViewBag.Name
@if (Model != null)
{
       foreach (var item in Model)
       {
        @Html.Partial("PartialView", item);
       }
 }